name: 'Security Scanning'

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  tsec:
    name: 'TFSec Scan'
    runs-on: ubuntu-latest
    # environment: 'Terraform Environment'
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: tfsec action
      uses: aquasecurity/tfsec-action@v1.0.3