name: 'Terraform'

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: 'Terraform Environment'
    uses: ./.github/workflows/terraform-setup.yml
    defaults:
      run:
        shell: bash
    steps:
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve -input=false

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: 'Terraform Environment'
    uses: ./.github/workflows/terraform-setup.yml
    needs: terraform-apply
    defaults:
      run:
        shell: bash
    steps:
    - name: Terraform Destroy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform destroy -target=junk -input=false
