name: 'Terraform'

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read
  issues: write

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: 'Terraform Environment'
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run setup jobs
      uses: ./.github/actions/terraform-setup
      with:
        aws_region: "us-east-1"
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Upload Terraform Plan
      id: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
    
    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: `Terraform plan uploaded: [terraform-plan](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})``
          })
            
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: 'Terraform Environment'
    needs: terraform-apply
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run setup jobs
      uses: ./.github/actions/terraform-setup
      with:
        aws_region: "us-east-1"
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Destroy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform destroy \
          -target aws_organizations_policy.deny_region_modify_except_root \
          -target aws_organizations_policy.deny_unused_regions \
          -target aws_organizations_policy.deny_unencrypted_buckets \
          -target aws_organizations_policy.deny_public_buckets \
          -input=false -auto-approve